export const data = [
    {
      orderId: 1231,
      product: "Bolt",
      price: 24,
      count: 1,
      profit: 10,
      date: "10-12-2023",
      dealer: "John",
    },
    {
      orderId: 2231,
      product: "Hinge",
      price: 33,
      count: 3,
      profit: 5,
      date: "9-11-2023",
      dealer: "Peter",
    },
    {
      orderId: 3231,
      product: "Suspension",
      price: 48,
      count: 2,
      profit: 5,
      date: "15-12-2023",
      dealer: "Susan",
    },
    {
      orderId: 1231,
      product: "Bolt",
      price: 24,
      count: 1,
      profit: 10,
      date: "10-12-2023",
      dealer: "John",
    },
    {
      orderId: 2231,
      product: "Hinge",
      price: 33,
      count: 3,
      profit: 5,
      date: "9-11-2023",
      dealer: "Peter",
    },
    {
      orderId: 3231,
      product: "Suspension",
      price: 48,
      count: 2,
      profit: 5,
      date: "15-12-2023",
      dealer: "Susan",
    },
    {
      orderId: 1231,
      product: "Bolt",
      price: 24,
      count: 1,
      profit: 10,
      date: "10-12-2023",
      dealer: "John",
    },
    {
      orderId: 2231,
      product: "Hinge",
      price: 33,
      count: 3,
      profit: 5,
      date: "9-11-2023",
      dealer: "Peter",
    },
    {
      orderId: 3231,
      product: "Suspension",
      price: 48,
      count: 2,
      profit: 5,
      date: "15-12-2023",
      dealer: "Susan",
    },
    {
      orderId: 1231,
      product: "Bolt",
      price: 24,
      count: 1,
      profit: 10,
      date: "10-12-2023",
      dealer: "John",
    },
    {
      orderId: 2231,
      product: "Hinge",
      price: 33,
      count: 3,
      profit: 5,
      date: "9-11-2023",
      dealer: "Peter",
    },
    {
      orderId: 3231,
      product: "Suspension",
      price: 48,
      count: 2,
      profit: 5,
      date: "15-12-2023",
      dealer: "Susan",
    },
    {
      orderId: 1231,
      product: "Bolt",
      price: 24,
      count: 1,
      profit: 10,
      date: "10-12-2023",
      dealer: "John",
    },
    {
      orderId: 2231,
      product: "Hinge",
      price: 33,
      count: 3,
      profit: 5,
      date: "9-11-2023",
      dealer: "Peter",
    },
    {
      orderId: 3231,
      product: "Suspension",
      price: 48,
      count: 2,
      profit: 5,
      date: "15-12-2023",
      dealer: "Susan",
    },
    {
      orderId: 1231,
      product: "Bolt",
      price: 24,
      count: 1,
      profit: 10,
      date: "10-12-2023",
      dealer: "John",
    },
    {
      orderId: 2231,
      product: "Hinge",
      price: 33,
      count: 3,
      profit: 5,
      date: "9-11-2023",
      dealer: "Peter",
    },
    {
      orderId: 3231,
      product: "Suspension",
      price: 48,
      count: 2,
      profit: 5,
      date: "15-12-2023",
      dealer: "Susan",
    },
    {
      orderId: 1001,
      product: "Air Filter",
      price: 10,
      count: 5,
      profit: 10,
      date: "15-10-2023",
      dealer: "Susan",
    },
    {
      orderId: 1001,
      product: "Air Filter",
      price: 10,
      count: 5,
      profit: 10,
      date: "15-01-2024",
      dealer: "Susan",
    },
  ];